layout_spectrum: 0.2553191
typography_spectrum: 0.3617021
color:
  saturation: 0.6829787
  lightness: 0.7148936
  brandStrength: 0.8071597
  rhythmicContrast: 0.5234042
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: 'Onponics '
